config/routes.rb
Textmining::Application.routes.draw do

get "users/new"
 resources :users
 resources :sessions, only: [:new, :create, :destroy]

root  'static_pages#index'

match '/', to: 'static_pages#index', via: 'get'
 match '/signup',  to: 'users#new',            via: 'get'
 match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
match '/help',    to: 'static_pages#help',    via: 'get'
match '/about',   to: 'static_pages#about',   via: 'get'
match '/contact', to: 'static_pages#contact', via: 'get'
match '/upload',   to: 'static_pages#upload',   via: 'get'
match '/uploaded',   to: 'static_pages#uploaded',   via: 'get'
match '/uploaded',   to: 'static_pages#uploaded',   via: 'post'
match '/uploadedtext',   to: 'static_pages#uploadedtext',   via: 'get'
match '/uploadedtext',   to: 'static_pages#uploadedtext',   via: 'post'

match '/inputtext',   to: 'static_pages#inputtext',   via: 'get'
match '/score', to: 'static_pages#score', via: 'get'
match '/score', to: 'static_pages#score', via: 'post'
match '/show',  to: 'users#show',         via: 'get'

end

app/models/articles.rb
class Articles < ActiveRecord::Base
belongs_to :user
  validates :user_id, presence: true
end

app/models/data_file.rb
class DataFile < ActiveRecord::Base
  def self.save(upload)
    name =  upload['file'].original_filename
    directory = "public/data"
    # create the file path
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['file'].read) }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
 before_save { self.email = email.downcase }
  before_create :create_remember_token

validates :name, presence: true, length: { maximum: 100 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#  protect_from_forgery with: :exception

protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
	sign_in user
	redirect_to  show_path
      # Sign the user in and redirect to the user's show page.
 

   else

      flash[:error] = 'Invalid email/password combination'
      redirect_to signin_path
    end
  end

  def destroy
sign_out
    redirect_to root_url
  end


private
    def user_params
      params.require(:user).permit(:name, :email, :password,
     :password_confirmation, :firstarticle ,:secondarticle)
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
require 'open-uri'
require 'pdf/reader'
require 'rubygems'
#  def index
 #    render :file => 'app\views\static_pages\upload.html.erb'
 # end

  def upload   

#    post = DataFile.save(params[:upload])
 #   render :text => "File has been uploaded successfully"
  end

def uploadedtext

if params[:first].empty? ||  params[:second].empty?
flash[:error] = "Please fill both TextArea!"
redirect_to inputtext_path
else
@first=params[:first]
@second=params[:second]

end
end

def uploaded

#require 'rubygems'
#require 'pdf-reader'

#uploaded_file =params[:file].original_filename
#reader = PDF::Reader.new(params[:file].path)
#str=""
#reader.pages.each do |page|
#str=str+" "+page.text
#end
#tf=str.gsub! "\n", " "
#@file_content =tf

if ((params[:file].nil?) || (params[:file1].nil?))
 flash[:error] = "Please choose both files!"

 redirect_to upload_path

else
File.open(params[:file].path, "rb") do |io|
 reader = PDF::Reader.new(io)
str=""
reader.pages.each do |page|
str=str+" "+page.text
end
tf=str.gsub! "\n", " "
@file_content =tf

end
#reader = PDF::Reader.new(params[:file1].path)
File.open(params[:file1].path, "rb") do |io|
  reader = PDF::Reader.new(io)
str=""
reader.pages.each do |page|
str=str+" "+page.text
end
tf1=str.gsub! "\n", " "
@file_content1 =tf1

end

end
#uploaded_file1 =params[:file1].original_filename
#reader = PDF::Reader.new(uploaded_file1)
#str1=""
#reader.pages.each do |page|
#str1=str1+" "+page.text
#end
#tf2=str1.gsub! "\n", " "
#@file_content1 =tf2  

#puts "file_content"

end

  def index
  end

  def help
  end

  def about
  end

  def contact
  end

  def score
        require './textmining.rb'

	@first = current_user.firstarticle
  	@second=current_user.secondarticle
	text=Textsimilarity.new
	@score=text.calculateSimilarity(@first,@second)
#	render :score
  end

def inputtext
	#@user=User.new		
end

#def new
	
#end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
#	 render "./static_pages/score.html.erb"
#	require './textmining.rb'
 #       @first = User.last.firstarticle
  #      @second=User.last.secondarticle
   #     text=Textsimilarity.new
    #    @score=text.calculateSimilarity(@first,@second)

#    render  "./static_pages/score.html.erb"
 end

  # GET /users/1
  # GET /users/1.json
  def show	
	@user = User.find_by(email: params[:email])
 # @user = User.find(params[:email])

	current_user=@user
 end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
   
@user = User.new(user_params)

if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Plagiarism Detector!"
      redirect_to @user
    else

      render 'new'
    end
#@user.save
#render 'show'


#redirect_to "/score"
   # render action: "./static_pages/score.html.erb"
# respond_to do |format|
#	format.html {redirect_to "/score"}  
#end
#redirect_to "/inputtext"

  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
    :password_confirmation, :firstarticle ,:secondarticle)
    end

#  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
 #   def user_params
  #    params.require(:user).permit(:name, :email, :firstarticle, 
#			:secondarticle)
 #   end
end

app/helpers/application_helper.rb
module ApplicationHelper
 # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Plagiarism Detector!"
    if page_title.empty?
      base_title
    else
      "#{base_title} : #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
 def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
def current_user=(user)
    @current_user = user
  end
 def signed_in?
    !current_user.nil?
  end

 def current_user
  remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/upload_controller_helper.rb
module UploadControllerHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/helpers/userhas_helper.rb
module UserhasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="">Avoid Plagiarism!</a>
    by Erfaneh Gharavi
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://en.wikipedia.org/wiki/Plagiarism">What is plagiarism!</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Plagiarism Detector!", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
	 <li><%= link_to "Home", current_user %></li>
	   <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Help", help_path %></li>

          <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
	 <li><%= link_to "Home", root_path %></li>
         <li><%= link_to "Help", help_path %></li>
	 <li><%= link_to "Sign in", signin_path %></li>

          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
 <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About us') %>
    <h1>Our Vision:</h1>
    <h2>
Reach world without any plagiarism:)
</h2>
    

<h1>Our Mission:</h1>
 <h2>
Create a powerful tool to detect documents similarity. 
</h2>


<h1>Our strategy:</h1>
 <h2>
Provide plagiarism detector service on cloud! 
</h2>

<h1>Our Technique:</h1>
 <h2>
Use Ruby On Rails to create Tool
</h2>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact us') %>
    <h1>Please Contact us !</h1>
<h2> 

Any suggestions or complaints will be appreciated!
<br>
<br>
<br>
Please send me your new Ideas, but Don't cheat :D

</h2>

<h1>
Email:
</h1>

<h3>


e.gharavi[at]ut.ac.ir

</h3>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
    <h1>Help</h1>
<h2>

Actually no help needed. Just sign up and after that everything is straight forward,

<br>
<br>
You can upload two PDF files for comparison or enter Text manually.

<br>
<br>
Remember that stop words like 'a', 'the', ... will be ommited during comparison.


</h2>
<br>
<h3>
 Note: For your information cosine similarity measure was used here.
</h3>

app/views/static_pages/index.html.erb
<div class="center hero-unit">
  <h1>Welcome to Plagiarism Detector App!</h1>

  <h2>
    This is the home page for our application which aim is to create a world
<br>
 without any plagiarism!
</h2>

<h4>

Please visit <%= link_to "Help" , help_path %> page for mor information.
  </h4>

  <%= link_to "Sign up and enjoy!", signup_path, class: "follow-button" %>
</div>

<%= link_to image_tag("pla.jpeg", alt: "Avoid Plagiarism"), '' %>

app/views/static_pages/inputtext.html.erb
<% provide(:title, 'Text Input') %>

<%= @user=current_user %>
<h1> Input Text </h1>
<h2> Please Enter your Text here for comparison! </h2>

<h3>
<label> First Article: </label>

<%=form_tag uploadedtext_path , :id=>"my" do %>

<%=text_area_tag "first"%>

<label> Second Article: </label>
<%=text_area_tag "second"%>
</h3>
<h3>
<%= submit_tag "Score", class: "follow-button" %>
</h3>
<%end %>

app/views/static_pages/score.html.erb
<% provide(:title, 'Score') %>

<h1>HOW MUCH SIMILAR ARE THEY...</h1>
<h2><label>These two documents are

<br>
<h1>
<%=@score%> 
<br>

%  similar! </label> 
</h1>


</h2>
<br>
<h1> The judgment is on your own :) </h1>

<h4>
<%= link_to "Back to text input", './inputtext',
                               class: "follow-button" %>
<br>
<br>

<%= link_to "Back to file upload", upload_path,
                                class: "follow-button" %>

</h4>

app/views/static_pages/upload.html.erb
<% provide(:title, 'Upload Files') %>

<h1>Upload Files Here:</h1>
<br>
<%= form_tag '/uploaded' , :multipart => true do %>
<h2>  <label for="file">Upload First Article</label> <%= file_field_tag "file" %>
</h2>
<br>
<h2>
  <label for="file1">Upload Second Article</label> <%= file_field_tag "file1" %>
</h2>
<br>
<h2> Attention:</h2> 
<h4>Some pdf files can not be read due to their structures!
 If confirmation page not appeared back to this page and try other files </h4>
<br>
<h3>

	<%= submit_tag  "upload" , class: "follow-button"%>
</h3>


<% end %>

app/views/static_pages/uploaded.html.erb
<% provide(:title, 'Content Confirmation') %>

<h2> Please Confirm files content: </h2>

<h3>
 <%= link_to "Confirm", score_path,
                               class: "follow-button" %>
</h3>
<br>
<h2>
<label>Content of first article</label>
</h2>

<p>
<%=@file_content%>
</p>

<br>
<br>
<h2>
<label>Content of Second article</label>
</h2>
<br>

<p>
<%=@file_content1%>
</p>

<%=current_user.update_attribute(:firstarticle, @file_content)%>
<%=current_user.update_attribute(:secondarticle, @file_content1)%>

<h3>
 <%= link_to "Confirm", score_path,
                                class: "follow-button" %>
</h3>

app/views/static_pages/uploadedtext.html.erb
<% provide(:title, 'Content Confirmation') %>


<h1> Please confirm contents </h1>

 <%= link_to "Confirm", score_path,
                                class: "follow-button" %>

<h2> Content of first article </h2>
<br>
<p>
<%=@first%>
</p>

<h2>Content of Second article</h2>

<br>
<p>
<%=@second%>
</p>

<%=current_user.update_attribute(:firstarticle, @first)%>
<%=current_user.update_attribute(:secondarticle, @second)%>


 <%= link_to "Confirm", score_path,
                                class: "follow-button" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :firstarticle %><br>
    <%= f.text_field :firstarticle %>
  </div>
  <div class="field">
    <%= f.label :secondarticle %><br>
    <%= f.text_field :secondarticle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Your personal information Here</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "follow-button" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user) %>
<h1> Welcome! :) </h1>
<br>
<h2> If you want to upload files click Upload files for comparison </h2>
<h2> If you want to Enter two Text manually click Enter text for comparison </h2>
<br>
<%@user=current_user%>
<p id="notice"><%= notice %></p>

<h3>
  <label>Name:</label>
</h3>
<h4> 
 <%= @user.name %>
</h4>

<h3>
  <label>Email:</label>
</h3>
<h4>
  <%= @user.email %>
</h4>

<br>


<%= link_to "Enter Text manually", inputtext_path,
                                 class: "follow-button" %>
<br>
<%= link_to "Upload Files", upload_path,
                                 class: "follow-button" %>

<br>


<%= link_to 'Edit', edit_user_path(@user) %> 